import {env} from '../assets/js/env';

export const environment = {
  production: true,
  ML_ARTIST_DISCOVERY_SEARCH_URL: env.ML_ARTIST_DISCOVERY_SEARCH_URL,
  ML_ARTIST_DISCOVERY_ARTIST_URL: env.ML_ARTIST_DISCOVERY_ARTIST_URL,
  ML_ARTIST_FBPAGE_SEARCH_URL: env.ML_ARTIST_FBPAGE_SEARCH_URL,
  ML_ARTIST_FBPAGE_GOOGLE_SEARCH_URL: env.ML_ARTIST_FBPAGE_GOOGLE_SEARCH_URL
};
