import {sysenv} from '../assets/js/env';

export const environment = {
  production: true,
  ML_ARTIST_DISCOVERY_SEARCH_URL: sysenv.ML_ARTIST_DISCOVERY_SEARCH_URL,
  ML_ARTIST_DISCOVERY_ARTIST_URL: sysenv.ML_ARTIST_DISCOVERY_ARTIST_URL,
  ML_ARTIST_FBPAGE_SEARCH_URL: sysenv.ML_ARTIST_FBPAGE_SEARCH_URL,
  ML_ARTIST_FBPAGE_GOOGLE_SEARCH_URL: sysenv.ML_ARTIST_FBPAGE_GOOGLE_SEARCH_URL,
};
